export const ACCEPT_TEAM_INVITE_REQUEST = "ACCEPT_TEAM_INVITE_REQUEST";
export const ACCEPT_TEAM_INVITE_SUCCESS = "ACCEPT_TEAM_INVITE_SUCCESS";
export const ACCEPT_TEAM_INVITE_FAIL = "ACCEPT_TEAM_INVITE_FAIL";

export const MY_TEAM_INVITES_SUCCESS = "MY_TEAM_INVITES_SUCCESS";
export const MY_TEAM_INVITES_FAIL = "MY_TEAM_INVITES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
